services:
  middleware:
    build:
      context: .
      dockerfile: dockerfile-node
    image: node-backend
    container_name: server
    command: node index.js
    restart: always
    environment:
      - PG_CONTAINER_NAME=oceandb
      - POSTGRES_USER=oceannft
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=oceannft
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=pg
      - BACKEND_PORT=6000
    ports:
      - '6000:6000'
    depends_on:
      - postgres
      
  proxy:
    image: nginx:latest
    restart: always

    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './build:/app'
    ports:
      - '8080:80'
    depends_on:
      - middleware

  postgres:
    build:
      context: .
      dockerfile: dockerfile-db
    image: "postgres-ocean"
    container_name: oceandb
    environment:
      POSTGRES_DB: oceannft
      POSTGRES_USER: oceannft
      POSTGRES_PASSWORD: '1234'
      PGDATA: '/data/ocean-vol'
    volumes:
       - oceanvol:/data/ocean-vol
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    oceanvol:
      external: true