services:
  middleware:
    build:
      context: .
      dockerfile: dockerfile-node
    image: node-backend
    container_name: backend
    command: node index.js
    restart: always
    environment:
      - PG_CONTAINER_NAME=pg
      - POSTGRES_USER=coinlist
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=coinlist
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=pg
      - BACKEND_PORT=5000
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      
  proxy:
    image: nginx:latest
    restart: always
    environment:
      - REACT_APP_BACKEND_BASE_URL=http://middleware:8080/backend/
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './build:/app'
    ports:
      - '8080:80'
    depends_on:
      - middleware

  postgres:
    build:
      context: .
      dockerfile: dockerfile-db
    image: "postgres-db"
    container_name: pg
    environment:
      POSTGRES_DB: coinlist
      POSTGRES_USER: coinlist
      POSTGRES_PASSWORD: '1234'
      PGDATA: '/data/postgres-tuto'
    volumes:
       - dbvol:/data/postgres-tuto
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    dbvol:
      external: true